'use strict';

//chiedo all'utente tramite prompt una parola o una frase

let userInput = prompt('Enter a word or a phrase. Is it Palindrome?');

// trasformo l'input in minuscolo per evitare errori durante il controllo

userInput = userInput.toLowerCase();

//stampo in console l'input utente

console.log('Word or phrase entered by the user:', userInput);

// funzione

function palindromeCheck(string) {

    // FAIL SAFE IN CASO DI FRASE : rimuovo tutti gli spazi presenti

    string = string.replaceAll(' ', '');

    // converto la stringa in array
    const arrayValues = string.split('');

    console.log('Array containing the split string: ', arrayValues);

    // inverto i valori dell'array
    const reverseArrayValues = arrayValues.reverse();

    console.log('Reversed array:', reverseArrayValues);

    // riconverto l'array in stringa
    const reverseString = reverseArrayValues.join('');

    console.log('String generated by joining all the array elements together: ', reverseString);

    // controllo se la stringa invertita é uguale all'input utente

    if (string === reverseString) {
        console.log('RESULT: It is a palindrome');
    }
    else {
        console.log('RESULT: It\'s not a palindrome');
    }

}

// invocazione della funzione

palindromeCheck(userInput);